language: python
sudo: false
python: 3.6
matrix:
  fast_finish: true
  allow_failures:
  - env:
    - TOX_ENV=pypy
    - TOX_ENV=build_docs
install:
- pip install --upgrade pip setuptools tox virtualenv coveralls
script:
- git branch -v
- git rev-list HEAD|wc -l
- tox
after_success: coveralls
after_failure:
- for X in .tox/$TOX_ENV/log/*; do echo "$X\n"; cat "$X"; echo "\n\n"; done
- echo "pip.log\n"; cat $HOME/.pip/pip.log
